import type { Quest } from './dsl'

// Season 0 quest catalog. 24 senior-calibrated quests across tracks A–E
// (A:6, B:5, C:6, D:5, E:2) plus one raid boss unlocked at 80% restore.
// Each quest restores exactly one tile group in District Alpha.

export const QUESTS: Quest[] = [
  // ── Track A — AI tools (6) ─────────────────────────────────────────────
  {
    id: 'a1',
    track: 'A',
    title: 'Wire an Agent Loop',
    difficulty: 'mid',
    sandbox: 'coding',
    hook: 'The Spire\'s dispatcher agent is stuck echoing its own thoughts. Give it hands.',
    brief: 'Implement an agent loop that (1) plans, (2) calls a tool, (3) observes the result, and (4) decides whether to stop. Bound the loop with a max-steps guard.',
    rubric: [
      { id: 'loop', label: 'Explicit plan→act→observe loop', weight: 0.4 },
      { id: 'tool', label: 'Calls at least one tool', weight: 0.3 },
      { id: 'guard', label: 'Bounded by a max-step / termination guard', weight: 0.3 },
    ],
    loot: { id: 'bp-agent-loop', name: 'Bounded Agent Loop', pattern: 'plan → act → observe with a hard step ceiling and a stop condition.' },
    tileUnlock: 'a1',
    grader: { kind: 'coding', language: 'ts', mustInclude: ['while', 'tool', 'step'], mustNotInclude: ['while (true)', 'while(true)'], minLines: 6 },
  },
  {
    id: 'a2',
    track: 'A',
    title: 'Build an Eval Harness',
    difficulty: 'senior',
    sandbox: 'coding',
    hook: 'Nobody trusts the new model. Prove it — or don\'t ship it.',
    brief: 'Write an eval harness that runs a suite of cases against a model fn, scores each, and reports an aggregate pass rate. Assertions must be data-driven, not hard-coded to one case.',
    rubric: [
      { id: 'cases', label: 'Iterates a case dataset', weight: 0.35 },
      { id: 'score', label: 'Scores + aggregates results', weight: 0.35 },
      { id: 'report', label: 'Emits a pass-rate / report', weight: 0.3 },
    ],
    loot: { id: 'bp-eval', name: 'Golden-Set Eval', pattern: 'dataset → run → score → aggregate → gate on regression.' },
    tileUnlock: 'a2',
    requires: ['a1'],
    grader: { kind: 'coding', language: 'ts', mustInclude: ['for', 'score', 'pass'], minLines: 8 },
  },
  {
    id: 'a3',
    track: 'A',
    title: 'Prompt & Tool Routing',
    difficulty: 'senior',
    sandbox: 'coding',
    hook: 'One monster prompt does everything badly. Split the brain.',
    brief: 'Implement a router that inspects a request and dispatches to the right specialized handler/tool. Include a default fallback path.',
    rubric: [
      { id: 'route', label: 'Routes on request shape/intent', weight: 0.5 },
      { id: 'fallback', label: 'Has a default / fallback branch', weight: 0.3 },
      { id: 'ext', label: 'New routes addable without rewrites', weight: 0.2 },
    ],
    loot: { id: 'bp-router', name: 'Intent Router', pattern: 'classify intent → table-dispatch → typed fallback.' },
    tileUnlock: 'a3',
    grader: { kind: 'coding', language: 'ts', mustInclude: ['switch', 'default', 'route'], minLines: 8 },
  },
  {
    id: 'a4',
    track: 'A',
    title: 'Cost & Latency Budget',
    difficulty: 'senior',
    sandbox: 'architecture',
    hook: 'Finance found the inference bill. Bring receipts, not vibes.',
    brief: 'Write a short ADR choosing a model tier + caching + fallback strategy under a fixed cost/latency budget. State the tradeoff you are accepting.',
    rubric: [
      { id: 'budget', label: 'Quantifies cost & latency targets', weight: 0.4 },
      { id: 'tradeoff', label: 'Names an explicit tradeoff', weight: 0.35 },
      { id: 'fallback', label: 'Degradation / fallback plan', weight: 0.25 },
    ],
    loot: { id: 'bp-budget', name: 'Inference Budget Card', pattern: 'tier + cache + degrade-gracefully within a hard $/latency ceiling.' },
    tileUnlock: 'a4',
    grader: { kind: 'architecture', requiredSections: ['Context', 'Decision', 'Tradeoff'], minWords: 90 },
  },
  {
    id: 'a5',
    track: 'A',
    title: 'Safe Tool Use',
    difficulty: 'staff',
    sandbox: 'coding',
    hook: 'The agent just tried to `rm -rf` a prod bucket. Put it on a leash.',
    brief: 'Implement a tool-call guard that validates arguments against an allowlist/policy and blocks destructive operations before execution. Return a structured deny reason.',
    rubric: [
      { id: 'validate', label: 'Validates args before execution', weight: 0.4 },
      { id: 'deny', label: 'Blocks destructive ops w/ reason', weight: 0.4 },
      { id: 'allow', label: 'Allowlist / policy driven', weight: 0.2 },
    ],
    loot: { id: 'bp-tool-guard', name: 'Tool Guardrail', pattern: 'validate → policy-check → allow/deny with a structured reason.' },
    tileUnlock: 'a5',
    grader: { kind: 'coding', language: 'ts', mustInclude: ['allow', 'deny', 'if'], minLines: 8 },
  },
  {
    id: 'a6',
    track: 'A',
    title: 'Retrieval Grounding',
    difficulty: 'senior',
    sandbox: 'coding',
    hook: 'The Spire hallucinates its own floor plan. Ground it in truth.',
    brief: 'Implement a retrieve-then-answer function: fetch top-k context, inject it, and cite which sources were used. No sources → say you don\'t know.',
    rubric: [
      { id: 'retrieve', label: 'Retrieves top-k context', weight: 0.4 },
      { id: 'cite', label: 'Cites the sources used', weight: 0.3 },
      { id: 'abstain', label: 'Abstains when no context', weight: 0.3 },
    ],
    loot: { id: 'bp-rag', name: 'Grounded Answer', pattern: 'retrieve top-k → inject → cite → abstain on empty.' },
    tileUnlock: 'a6',
    grader: { kind: 'coding', language: 'ts', mustInclude: ['retrieve', 'context', 'cite'], minLines: 8 },
  },

  // ── Track B — MCP (5) ──────────────────────────────────────────────────
  {
    id: 'b1',
    track: 'B',
    title: 'Design an MCP Server',
    difficulty: 'mid',
    sandbox: 'mcp',
    hook: 'The Annex speaks a dozen dialects. Give it one contract.',
    brief: 'Submit an MCP server manifest (JSON) exposing at least two tools. Each tool needs a name, description, and input schema.',
    rubric: [
      { id: 'server', label: 'Declares a server + tools list', weight: 0.4 },
      { id: 'schema', label: 'Each tool has an input schema', weight: 0.4 },
      { id: 'desc', label: 'Tools are described', weight: 0.2 },
    ],
    loot: { id: 'bp-mcp-server', name: 'MCP Server Skeleton', pattern: 'server → tools[] with name + description + inputSchema.' },
    tileUnlock: 'b1',
    grader: { kind: 'mcp', requiredTopLevel: ['server', 'tools'], requiredToolFields: ['name', 'description', 'inputSchema'], requireAuthScopes: false },
  },
  {
    id: 'b2',
    track: 'B',
    title: 'Auth Scopes for Tools',
    difficulty: 'senior',
    sandbox: 'mcp',
    hook: 'Every tool can do everything. That\'s not access control, that\'s a fire.',
    brief: 'Extend your MCP manifest so each tool declares the minimal auth scopes it requires. Add a top-level scopes registry.',
    rubric: [
      { id: 'scopes', label: 'Per-tool required scopes', weight: 0.5 },
      { id: 'registry', label: 'Declared scope registry', weight: 0.3 },
      { id: 'least', label: 'Scopes are minimal per tool', weight: 0.2 },
    ],
    loot: { id: 'bp-mcp-scopes', name: 'Scoped Tools', pattern: 'each tool declares least-privilege scopes against a central registry.' },
    tileUnlock: 'b2',
    requires: ['b1'],
    grader: { kind: 'mcp', requiredTopLevel: ['server', 'tools', 'scopes'], requiredToolFields: ['name', 'scopes'], requireAuthScopes: true },
  },
  {
    id: 'b3',
    track: 'B',
    title: 'Tool Contracts',
    difficulty: 'senior',
    sandbox: 'mcp',
    hook: 'Callers guess your outputs. Guesses become outages.',
    brief: 'Give each MCP tool an explicit output schema and an errors list so callers can program against the contract.',
    rubric: [
      { id: 'output', label: 'Each tool has an output schema', weight: 0.5 },
      { id: 'errors', label: 'Declares error cases', weight: 0.3 },
      { id: 'name', label: 'Stable tool names', weight: 0.2 },
    ],
    loot: { id: 'bp-mcp-contract', name: 'Tool Contract', pattern: 'name + inputSchema + outputSchema + errors[] = a programmable contract.' },
    tileUnlock: 'b3',
    requires: ['b1'],
    grader: { kind: 'mcp', requiredTopLevel: ['server', 'tools'], requiredToolFields: ['name', 'outputSchema', 'errors'], requireAuthScopes: false },
  },
  {
    id: 'b4',
    track: 'B',
    title: 'Failure Modes & Fault Injection',
    difficulty: 'staff',
    sandbox: 'architecture',
    hook: 'A fixture server just went dark mid-call. What does your host do?',
    brief: 'Write a short ADR describing how your MCP host handles tool timeouts, partial failures, and retries under fault injection. Include a blast-radius limit.',
    rubric: [
      { id: 'timeout', label: 'Timeout & retry policy', weight: 0.35 },
      { id: 'blast', label: 'Bounds blast radius', weight: 0.35 },
      { id: 'degrade', label: 'Partial-failure degradation', weight: 0.3 },
    ],
    loot: { id: 'bp-mcp-faults', name: 'Fault-Tolerant Host', pattern: 'timeout + bounded retries + circuit-break to cap blast radius.' },
    tileUnlock: 'b4',
    requires: ['b1'],
    grader: { kind: 'architecture', requiredSections: ['Context', 'Decision', 'Failure'], minWords: 90 },
  },
  {
    id: 'b5',
    track: 'B',
    title: 'Multi-Server Orchestration',
    difficulty: 'staff',
    sandbox: 'mcp',
    hook: 'Three servers, one goal. Who\'s in charge?',
    brief: 'Submit an orchestration manifest that composes at least two MCP servers, declares which server owns which tools, and defines a routing rule between them.',
    rubric: [
      { id: 'servers', label: 'Composes 2+ servers', weight: 0.4 },
      { id: 'ownership', label: 'Tool ownership per server', weight: 0.35 },
      { id: 'routing', label: 'Routing rule declared', weight: 0.25 },
    ],
    loot: { id: 'bp-mcp-orch', name: 'Server Mesh', pattern: 'servers[] own tools; a router picks the owner per intent.' },
    tileUnlock: 'b5',
    requires: ['b1', 'b3'],
    grader: { kind: 'mcp', requiredTopLevel: ['servers', 'routing'], requiredToolFields: ['name', 'owner'], requireAuthScopes: false },
  },

  // ── Track C — Cloud infra (6) ──────────────────────────────────────────
  {
    id: 'c1',
    track: 'C',
    title: 'IAM Least-Privilege',
    difficulty: 'mid',
    sandbox: 'cloud',
    hook: 'The Annex hands out root like candy. Lock the vault.',
    brief: 'Submit a policy plan granting a service only the specific actions/resources it needs. No wildcards on actions or resources.',
    rubric: [
      { id: 'scoped', label: 'Actions scoped to need', weight: 0.4 },
      { id: 'resource', label: 'Resources scoped by ARN/name', weight: 0.35 },
      { id: 'nowild', label: 'No action wildcards', weight: 0.25 },
    ],
    loot: { id: 'bp-iam', name: 'Least-Privilege Policy', pattern: 'explicit allow on named actions + named resources; deny wildcards.' },
    tileUnlock: 'c1',
    grader: { kind: 'cloud', requiredPolicies: ['allow', 'resource', 'action'], forbidden: ['"*"', "'*'", 'Action: *'], minLines: 6 },
  },
  {
    id: 'c2',
    track: 'C',
    title: 'Network Segmentation',
    difficulty: 'senior',
    sandbox: 'cloud',
    hook: 'Everything can reach everything. That\'s a lateral-movement buffet.',
    brief: 'Submit a network plan with public/private subnets, security-group rules that default-deny, and an explicit egress policy.',
    rubric: [
      { id: 'subnets', label: 'Public/private split', weight: 0.35 },
      { id: 'deny', label: 'Default-deny ingress', weight: 0.4 },
      { id: 'egress', label: 'Explicit egress policy', weight: 0.25 },
    ],
    loot: { id: 'bp-net', name: 'Segmented Network', pattern: 'private-by-default subnets, default-deny SGs, explicit egress.' },
    tileUnlock: 'c2',
    grader: { kind: 'cloud', requiredPolicies: ['subnet', 'deny', 'egress'], forbidden: ['0.0.0.0/0 ingress'], minLines: 6 },
  },
  {
    id: 'c3',
    track: 'C',
    title: 'Observability Baseline',
    difficulty: 'senior',
    sandbox: 'cloud',
    hook: 'When the Annex fell, no one saw it happen. Fix the blindness.',
    brief: 'Submit a plan defining the metrics, logs, and traces you export, plus at least one alert with a threshold and an SLO it protects.',
    rubric: [
      { id: 'mlt', label: 'Metrics + logs + traces', weight: 0.4 },
      { id: 'alert', label: 'Alert with threshold', weight: 0.35 },
      { id: 'slo', label: 'Tied to an SLO', weight: 0.25 },
    ],
    loot: { id: 'bp-o11y', name: 'O11y Baseline', pattern: 'metrics+logs+traces → SLO-backed alerts with real thresholds.' },
    tileUnlock: 'c3',
    grader: { kind: 'cloud', requiredPolicies: ['metric', 'log', 'trace', 'alert'], forbidden: [], minLines: 6 },
  },
  {
    id: 'c4',
    track: 'C',
    title: 'Deploy & Rollback',
    difficulty: 'senior',
    sandbox: 'cloud',
    hook: 'Ship button works. The un-ship button? Untested.',
    brief: 'Submit a deploy plan with a progressive rollout (canary/blue-green), a health gate, and an automatic rollback trigger.',
    rubric: [
      { id: 'progressive', label: 'Canary / blue-green rollout', weight: 0.4 },
      { id: 'gate', label: 'Health gate before promote', weight: 0.3 },
      { id: 'rollback', label: 'Automatic rollback trigger', weight: 0.3 },
    ],
    loot: { id: 'bp-deploy', name: 'Safe Rollout', pattern: 'canary → health gate → auto-rollback on breach.' },
    tileUnlock: 'c4',
    requires: ['c3'],
    grader: { kind: 'cloud', requiredPolicies: ['canary', 'rollback', 'health'], forbidden: [], minLines: 6 },
  },
  {
    id: 'c5',
    track: 'C',
    title: 'Cost Guardrails',
    difficulty: 'senior',
    sandbox: 'cloud',
    hook: 'The lab ran a GPU fleet all weekend. For nothing.',
    brief: 'Submit a plan with a budget, an alert at a spend threshold, and an automated action (scale-to-zero / TTL teardown) to cap runaway cost.',
    rubric: [
      { id: 'budget', label: 'Defines a budget', weight: 0.35 },
      { id: 'alert', label: 'Spend-threshold alert', weight: 0.3 },
      { id: 'auto', label: 'Automated cost cap action', weight: 0.35 },
    ],
    loot: { id: 'bp-cost', name: 'Cost Guardrail', pattern: 'budget + threshold alert + auto scale-to-zero / TTL teardown.' },
    tileUnlock: 'c5',
    grader: { kind: 'cloud', requiredPolicies: ['budget', 'alert', 'teardown'], forbidden: [], minLines: 6 },
  },
  {
    id: 'c6',
    track: 'C',
    title: 'Multi-Region Sketch',
    difficulty: 'staff',
    sandbox: 'architecture',
    hook: 'One region, one earthquake, zero city. Spread the risk.',
    brief: 'Write an ADR sketching a multi-region topology: what data replicates, the failover trigger, and the consistency tradeoff you accept.',
    rubric: [
      { id: 'topology', label: 'Region topology + replication', weight: 0.4 },
      { id: 'failover', label: 'Failover trigger', weight: 0.3 },
      { id: 'consistency', label: 'Consistency tradeoff stated', weight: 0.3 },
    ],
    loot: { id: 'bp-multiregion', name: 'Multi-Region Card', pattern: 'replicate the durable core, fail over on health, accept bounded staleness.' },
    tileUnlock: 'c6',
    requires: ['c2'],
    grader: { kind: 'architecture', requiredSections: ['Context', 'Decision', 'Tradeoff'], minWords: 100 },
  },

  // ── Track D — Architecture (5) ─────────────────────────────────────────
  {
    id: 'd1',
    track: 'D',
    title: 'Write a Real ADR',
    difficulty: 'mid',
    sandbox: 'architecture',
    hook: 'Decisions live in someone\'s memory and leave when they do.',
    brief: 'Write an ADR for a decision of your choice with Context, Decision, Consequences, and at least one rejected alternative.',
    rubric: [
      { id: 'sections', label: 'Context/Decision/Consequences', weight: 0.5 },
      { id: 'alt', label: 'A rejected alternative', weight: 0.3 },
      { id: 'prose', label: 'Substantive, not boilerplate', weight: 0.2 },
    ],
    loot: { id: 'bp-adr', name: 'ADR Template', pattern: 'Context → Decision → Consequences → Alternatives, dated & owned.' },
    tileUnlock: 'd1',
    grader: { kind: 'architecture', requiredSections: ['Context', 'Decision', 'Consequences', 'Alternative'], minWords: 90 },
  },
  {
    id: 'd2',
    track: 'D',
    title: 'Service Boundaries',
    difficulty: 'senior',
    sandbox: 'architecture',
    hook: 'The monolith and the microservices are both angry at you.',
    brief: 'Write an ADR defining a service boundary: what it owns, its public contract, and what it explicitly does NOT own. Justify the seam.',
    rubric: [
      { id: 'owns', label: 'Clear ownership + contract', weight: 0.4 },
      { id: 'notowns', label: 'Explicit non-ownership', weight: 0.3 },
      { id: 'seam', label: 'Justifies the seam', weight: 0.3 },
    ],
    loot: { id: 'bp-boundary', name: 'Boundary Card', pattern: 'own data + contract, name what you refuse to own, defend the seam.' },
    tileUnlock: 'd2',
    requires: ['d1'],
    grader: { kind: 'architecture', requiredSections: ['Context', 'Decision', 'Boundary'], minWords: 100 },
  },
  {
    id: 'd3',
    track: 'D',
    title: 'Consistency Model',
    difficulty: 'staff',
    sandbox: 'architecture',
    hook: 'Two users, two truths, one very confused ledger.',
    brief: 'Write an ADR choosing a consistency model (strong / eventual / read-your-writes) for a specific feature, and how clients cope with the choice.',
    rubric: [
      { id: 'model', label: 'Names the consistency model', weight: 0.4 },
      { id: 'why', label: 'Justifies vs alternatives', weight: 0.3 },
      { id: 'client', label: 'Client coping strategy', weight: 0.3 },
    ],
    loot: { id: 'bp-consistency', name: 'Consistency Card', pattern: 'pick the weakest model that still keeps the invariant users can see.' },
    tileUnlock: 'd3',
    requires: ['d1'],
    grader: { kind: 'architecture', requiredSections: ['Context', 'Decision', 'Tradeoff'], minWords: 100 },
  },
  {
    id: 'd4',
    track: 'D',
    title: 'Migration Plan',
    difficulty: 'senior',
    sandbox: 'architecture',
    hook: 'Big-bang the schema and pray. Or... don\'t.',
    brief: 'Write an ADR for a zero-downtime migration using expand/contract, including a backfill step and a rollback path.',
    rubric: [
      { id: 'expand', label: 'Expand/contract phases', weight: 0.4 },
      { id: 'backfill', label: 'Backfill strategy', weight: 0.3 },
      { id: 'rollback', label: 'Rollback path', weight: 0.3 },
    ],
    loot: { id: 'bp-migration', name: 'Expand/Contract Card', pattern: 'add new → dual-write → backfill → cut over → contract, reversible each step.' },
    tileUnlock: 'd4',
    requires: ['d1'],
    grader: { kind: 'architecture', requiredSections: ['Context', 'Decision', 'Rollback'], minWords: 100 },
  },
  {
    id: 'd5',
    track: 'D',
    title: 'AI Feature in an Existing System',
    difficulty: 'staff',
    sandbox: 'architecture',
    hook: 'Product wants "AI" bolted onto a 9-year-old service by Friday.',
    brief: 'Write an ADR adding an AI feature to an existing system: where it plugs in, the failure/fallback when the model is down, and the eval gate before rollout.',
    rubric: [
      { id: 'seam', label: 'Integration seam identified', weight: 0.35 },
      { id: 'fallback', label: 'Non-AI fallback path', weight: 0.35 },
      { id: 'eval', label: 'Eval gate before rollout', weight: 0.3 },
    ],
    loot: { id: 'bp-ai-feature', name: 'AI Retrofit Card', pattern: 'add behind a seam + non-AI fallback + eval gate before ramp.' },
    tileUnlock: 'd5',
    requires: ['d1'],
    grader: { kind: 'architecture', requiredSections: ['Context', 'Decision', 'Fallback'], minWords: 110 },
  },

  // ── Track E — Advanced SWE (2) ─────────────────────────────────────────
  {
    id: 'e1',
    track: 'E',
    title: 'Performance Incident',
    difficulty: 'senior',
    sandbox: 'coding',
    hook: 'p99 just tripled. The graphs are on fire. Go.',
    brief: 'Given a hot path, implement a fix that removes an O(n) per-call cost — e.g. memoize, batch, or replace a linear scan with a lookup. Keep behavior identical.',
    rubric: [
      { id: 'hotpath', label: 'Targets the hot path', weight: 0.4 },
      { id: 'complexity', label: 'Reduces per-call complexity', weight: 0.4 },
      { id: 'same', label: 'Preserves behavior', weight: 0.2 },
    ],
    loot: { id: 'bp-perf', name: 'Hot-Path Card', pattern: 'measure → cut the per-call cost (cache/batch/index) → verify identical output.' },
    tileUnlock: 'e1',
    grader: { kind: 'coding', language: 'ts', mustInclude: ['Map', 'cache'], mustNotInclude: ['for (', 'for('], minLines: 8 },
  },
  {
    id: 'e2',
    track: 'E',
    title: 'API Evolution',
    difficulty: 'staff',
    sandbox: 'architecture',
    hook: 'Break the API, break a thousand integrations. Evolve it instead.',
    brief: 'Write an ADR for evolving a public API without breaking clients: versioning strategy, deprecation policy, and compatibility guarantees.',
    rubric: [
      { id: 'version', label: 'Versioning strategy', weight: 0.4 },
      { id: 'deprecate', label: 'Deprecation policy', weight: 0.3 },
      { id: 'compat', label: 'Compatibility guarantees', weight: 0.3 },
    ],
    loot: { id: 'bp-api-evo', name: 'API Evolution Card', pattern: 'additive-by-default, version on break, deprecate on a clock, never surprise clients.' },
    tileUnlock: 'e2',
    grader: { kind: 'architecture', requiredSections: ['Context', 'Decision', 'Compatibility'], minWords: 100 },
  },

  // ── Raid boss — unlocked at 80% district restore ───────────────────────
  {
    id: 'raid',
    track: 'A',
    title: 'RAID: The Cascading Incident',
    difficulty: 'staff',
    sandbox: 'architecture',
    hook: 'An agent misbehaves in prod, an MCP tool blast-radius spreads, and the only fix is a cloud rollback under a ticking clock. All at once.',
    brief: 'Write an incident command ADR that (1) contains the misbehaving agent, (2) bounds the MCP tool blast radius, and (3) executes a cloud rollback decision — with the order of operations and the one metric you watch to call it resolved.',
    rubric: [
      { id: 'contain', label: 'Contains the agent', weight: 0.3 },
      { id: 'blast', label: 'Bounds MCP blast radius', weight: 0.25 },
      { id: 'rollback', label: 'Cloud rollback decision', weight: 0.25 },
      { id: 'order', label: 'Ordered ops + resolve metric', weight: 0.2 },
    ],
    loot: { id: 'bp-raid', name: 'Incident Commander', pattern: 'contain → bound blast radius → rollback → watch one North-Star metric to close.' },
    tileUnlock: 'raid',
    raid: true,
    unlockAt: 0.8,
    grader: { kind: 'architecture', requiredSections: ['Contain', 'Blast', 'Rollback', 'Resolve'], minWords: 130 },
  },
]

export const NON_RAID_QUESTS = QUESTS.filter((q) => !q.raid)
export const TOTAL_RESTORABLE = QUESTS.length // 24 quests + raid tile = 25 tile groups

export function questById(id: string): Quest | undefined {
  return QUESTS.find((q) => q.id === id)
}
